# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 14
    - nodejs_version: 12
    - nodejs_version: 10

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --ignore-scripts

test_script:
  - node --version
  - npm --version
  - npm test
  - npm run example:default
